metrumresearchgroup/bbi

.gitignore, cmd/local.go, cmd/root.go, cmd/run.go, configlib/config.go
* Random is initialized off of the timer during root init
* `--delay` flag introduced with default value of 0
* If delay value in configuration is greater than default:
* A random integer between 1 and the provided delay is selected
* This avoids synchronization. If you just specify a delay of 4 and 4 seconds is selected, all of the jobs will begin execution after waiting 4 seconds. This would still yield the IO problems. Just on a delay
* If debug is set, it will display the random seconds elected for delay
=> Updating with a randomized timer for local mode execution

cmd/local.go, cmd/nonmem.go, cmd/sge.go, configlib/config.go
Changing process to look for config in local directory or a provided config.  Not waiting to locate the models allows us to set the config item up front and pass a pointer to it to all nonmem models (or any other implementation) underneath it
=> Moving config up front

.gitignore, cmd/bbi/.gitignore, cmd/local.go, cmd/root.go, cmd/run.go, cmd/sge.go, configlib/config.go
Adds the following:
- If `json` is set as a flag, logging for logrus will use a JsonFormatter
- if `logFile` is set, we will write out to that file as well as stdout via multiwriter
- If the file is relative, (ie `babylon_output.log`) we will write it specifcally to that location and store the relative reference
- If the file is absolute, we will write to the absolute reference and store it in the config
=> Json logging

cmd/nonmem.go, cmd/nonmem_test.go
During `newNonMemModel` (Specifically selected because the arguments have been expanded), the model file is read and checked to see:
- Does It Contain a `$DATA` line
- Does that line contain a target (IE a File)
- Is the file accessible
If any of the above are false, it bubbles up an error and the application halts, letting the user know something was wrong with the data requested by the model.
=> Notify users of issues with data

cmd/nonmem.go, cmd/root.go, validation.json
Previously had too shallow of an approach, purely looking at stripping a single directory layer off the original path during certain scenarios. This worked in our simple test scenarios, but in complex scenarios such as the Metrum boiler plate, it would never work. 
Now 
* We navigate to the original path (where the model is now)
* Read the data line from the model
* If the extension is `ctl` and `createChildDirs` is true (normal execution)
* we strip a '../' from the data path line to find out where the file is in _current_ context
* Also added something to handle the fact that macOS uses a symlink to /tmp from /private/tmp. 
* From the perspective of the original model path we translate the "../../../..*.csv" line into the absolute path. That's what we now try to load and see if it can …
=> Changing how data file is located

.drone.yml, cmd/local.go, cmd/nonmem.go
When running with`--nmqual`, errors are generated in the output indicating the source model could not be hashed
During operation in the local branch, we copy the model, rename it to a `*.ctl`. This is because the NMQual operation requires a filename ending with CTL. At this point, however, we have no stored reference back to the original `.mod` or `.whatever` file.  So the hash tries to find a `.ctl` file in the original source directory (which may not exist). 
We already had an `OriginalPath` member of the `NonMemModel` struct, so I added an `OriginalModel` field, which is populated when all of the models are created from arguments. During hashing operations we always go back to the `OriginalPath`/`OriginalModel` to accurately get a model hash.
=> Fixing failure to hash source model for NMQual

cmd/bbi/goreleaser.yml
Several goreleaser changes:
* Addition of `extldflags -static`
* Addition of CGO_ENABLED=0 variable during build
* Update of release section to automatically mark non standard releases as pre-release
* This means that the "latest" link will still point to the latest production version
* v2.1.0 would be a production tag while v2.1.1-rc4 would be marked as pre-release automatically
* Updated the changelog section to exclude commits beginning with `ci:` or `docs:` 
I verified with `2.1.1-rc2` that this now works. The Linux binary works fine as downloaded and also that my `ci:` commit was excluded from the change log.
=> Goreleaser updates

cmd/run.go, cmd/sge.go
* Makes sure that before Qsub operations the provided additional post-work variables are added to the command execution environment for `qsub`
* Makes sure that the environment is appended to execution environment for the post work script
* Also make sure `qsub` uses the full path to the `grid.sh` script as opposed to just navigating to the directory and executing. Removes one more IO concern per operation
=> Making sure the additional environment variables end up in SGE Environment

parsers/nmparser/diagonal_elements.go, parsers/nmparser/utils.go, utils/io.go
We had an example furnished by @timwaterhouse of a model with 102 ETA's that parsed into an empty parameter table. 
The issue was that `ReadParamsAndOutputFromExt()` had an uncaught `bufio.ErrTooLong` because the lines in the `.ext` were longer than the buffer allowed and that was causing it to return an empty array that eventually got passed in to `ParametersData`. 
Increasing the buffer max solved the issue. His (very large) model had an average line size of ~75k. As far as I can see there is not technically a max for how big the lines could be, but I bumped it to 256k which should be plenty big.
=> Debugging issue Tim W found with empty parameter table

parsers/nmparser/parse_run_details.go, parsers/nmparser/parse_run_details_test.go, parsers/nmparser/structs.go
In gh-227, @dpolhamus reported that the number of data records wasn't being set properly when `$INFN` is used.  The lst file doesn't have the "TOT. NO. OF DATA RECS:" line that `ParseRunDetails` looks for, but there is a "NO. OF DATA RECS IN DATA SET:" line.  The last commit of this series falls back to using that value, assuming there is only one "NO. OF DATA RECS IN DATA SET:" line and that its value is a reasonable value for `NumberOfDataRecords`.
The first two commits are related fixes (or at least what I think are fixes).  One of them gets the tests in `parsers/nmparser/parse_run_details_test.go` to a passing state.  @seth127, would you prefer that I drop these commits and add the test in metrumresearchgroup/bbitest instead?
(Also, I'm being a bit lazy with the new test and …
=> ParseRunDetails: parse NumberOfDataRecords for $INFN output

cmd/clean.go, cmd/covcor.go, cmd/init.go, cmd/local.go, cmd/nonmem.go, cmd/project.go, cmd/reclean.go, cmd/root.go, cmd/run.go, cmd/scaffold.go, cmd/sge.go, cmd/summary.go, cmd/version.go
Working from Eli's "Converting cobra style to testable components"
writeup, convert all `var XCmd = &cobra.Command` cases to avoid
`init()` and instead use `NewXcmd()`.  All the changes in root.go
except for the new `AddCommand()` calls are the result of applying
Eli's patch from the writeup.
---
I've done scattered testing of the executable and things seem wired up correctly.
```
$ bbi version
develop-2021-09-08T18:16:40-0400
$ head bbi.yaml
head: cannot open 'bbi.yaml' for reading: No such file or directory
$ bbi init
$ head -2 bbi.yaml
bbi_binary: /Users/KyleM/go/bin/bbi
clean_lvl: 1
$ bbi nonmem summary inst/model/nonmem/basic/1/1 | head -2
LEM PK model 1 cmt base
Dataset: ../../../../extdata/acop.csv
$ touch 1.mod
$ bbi nonmem clean *.mod
$ ls 1.mod
ls: cannot access '1.mod': No such …
```
=> cmd: convert cobra style commands to testable components

validation/requirements.yaml, validation/stories.yaml
Moving validation stories and requirements into YAML files in the repo, as opposed to external Googlesheets.
Below is some sample R code to generate validation docs from these YAML files (and test results that are dumped to S3 from our drone CI). The intention is to add something like this as another step in the CI that will generate the docs and dump them to S3 anytime a tag is pushed.
```r
library(mrgvalprep)
library(mrgvalidate)
test_dir <- "test_output"
test_res <- parse_golang_test_json(file.path(test_dir, "results.json"))
readr::write_csv(test_res, file.path(test_dir, "summary.csv"))
spec <- read_spec_yaml(
"stories.yaml",
"requirements.yaml"
)
create_validation_docs(
"bbi",
"3.1.1.9000",
spec,
auto_test_dir = test_dir,
)
```
=> Adding stories.yaml and requirements.yaml to repo

integration/README.md
integration/README.md links to
https://github.com/metrumresearchgroup/bbi/blob/develop/.drone.yml
That "develop" part needs to be updated because we're going to remove
the `develop` branch and start using `main` as the base for topic
branches.  But using the full URL here is a holdover from when this
file was in the bbitest repo prior to 6efbe54 (Merge bbitest #242,
2021-09-21).  Switch to using a relative link.
=> README.md: update .drone.yml link

.drone.yml, parsers/nmparser/parse_run_details.go
Drone's lint phase is passing with no warnings, but the latest version
of golangci-lint (which I have installed locally) shows a "variable
'tokens' is only used in the if-statement" warning.  Catch drone up
with the latest release so that its results are more likely to align
with what developers see locally.
=> drone: update to latest golangci-lint

cmd/reclean.go, cmd/root.go, integration/bbi_reclean_test.go
This small PR fixes the following error that I noticed when looking into another issue:
```
$ bbi nonmem reclean
panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
[...]
```
With this PR, that becomes
```
$ bbi nonmem reclean
Error: must specify one positional argument, a directory
Usage:
bbi nonmem reclean [flags] <directory>
Flags:
[...]
```
It also fixes the more general issue of bbi double printing errors messages for `RunE` commands (mentioned in https://github.com/metrumresearchgroup/bbi/pull/272#discussion_r932278348)
Note that this PR uses gh-272 as the base, so this shouldn't be merged before that PR.  That was done just to piggyback off of its last commit (e1e1bda) that quiets the linter (the tests from the PR trigger the same issue independently).
=> reclean: avoid index error if no positional argument is specified

cmd/nonmem.go
nmfe's -prdefault and -tprdefault have fields in NMFEOptions (since
ac48a49, 2020-02-16) and are considered by processNMFEOptions() (since
3583755, 2020-02-16), but they aren't exposed as command line flags.
That appears to just be an oversight.  Add corresponding --prdefault
and --tprdefault flags to `bbi nonmem`.
Re: #262
Re: #263
---
```
$ bbi nonmem run local --nm_version=nm74gf --maxlim=3 --overwrite --prdefault inst/model/nonmem/basic/1.ctl
Error: unknown flag: --prdefault
Usage:
bbi nonmem run local [flags]
[...]
```
```
$ bbi nonmem run local --nm_version=nm74gf --maxlim=3 --overwrite --tprdefault inst/model/nonmem/basic/1.ctl
Error: unknown flag: --tprdefault
Usage:
bbi nonmem run local [flags]
[...]
```
```
$ bbi nonmem run local --nm_version=nm74gf --maxlim=3 --overwrite …
```
=> nonmem: expose PRDefault and TPRDefault as command line options

cmd/nonmem.go, cmd/nonmem_test.go, configlib/config.go, integration/init_test.go, validation/requirements.yaml, validation/stories.yaml
This PR makes it so that `-maxlim=2` is passed to `nmfe` by default, following @kylebaron's recommendation.
Closes #262.
=> nonmem: pass -maxlim=2 to nmfe by default

cmd/nonmem.go, cmd/run.go, docs/bbi/nonmem/run/run.md
These are two minor typos that have been pointed out in issues.  I want to get the `--nmqual` in before updating bbr's `BBI_ARGS` value (which inherits the same typo).
=> nonmem: fix two help output typos

integration/testdata/bbi_summary/aa_golden_files/12.golden.json, integration/testdata/bbi_summary/aa_golden_files/12.golden.txt, integration/testdata/bbi_summary/aa_golden_files/66.golden.json, integration/testdata/bbi_summary/aa_golden_files/66.golden.txt, integration/testdata/bbi_summary/aa_golden_files/acop-iov.golden.json, integration/testdata/bbi_summary/aa_golden_files/acop-iov.golden.txt, integration/testdata/bbi_summary/aa_golden_files/acop-nan.golden.json, integration/testdata/bbi_summary/aa_golden_files/acop-nan.golden.txt, integration/testdata/bbi_summary/aa_golden_files/acop.golden.json, integration/testdata/bbi_summary/aa_golden_files/acop.golden.txt, integration/testdata/bbi_summary/aa_golden_files/acop_no_grd.golden.json, integration/testdata/bbi_summary/aa_golden_files/acop_no_grd.golden.txt, integration/testdata/bbi_summary/aa_golden_files/iovmm.golden.json, integration/testdata/bbi_summary/aa_golden_files/iovmm.golden.txt, integration/testdata/bbi_summary/aa_golden_files/multiple-models-error.golden.json, integration/testdata/bbi_summary/aa_golden_files/multiple-models.golden.json, integration/testdata/bbi_summary/aa_golden_files/multiple-models.golden.txt, integration/testdata/bbi_summary/aa_golden_files/onlysim.golden.json, integration/testdata/bbi_summary/aa_golden_files/onlysim.golden.txt, parsers/nmparser/parse_run_details.go, parsers/nmparser/parse_run_details_test.go, validation/requirements.yaml, validation/stories.yaml
This PR fixes the `$PROBLEM` parsing issue described in gh-201.  The last commit is the main one of interest.
Note that there are lots of file changes, but most of those are just golden files where "LEM"s are being dropped:
```
$ git diff --name-only main.. ':!*golden*'
parsers/nmparser/parse_run_details.go
parsers/nmparser/parse_run_details_test.go
```
=> nmparser: handle $PROBLEM in addition to $PROB

NEWS.md, cmd/NEWS.md
Entries for https://github.com/metrumresearchgroup/bbi/compare/v3.1.1...9fdf0af568f17028cb35fdbd3bf3d12991653fea
<details>
<summary>PR list</summary>
```
+ included
- not included
-  207e040a Merge pull request #265 from metrumresearchgroup/validation_yaml
-  a7275962 Merge pull request #267 from metrumresearchgroup/bbitest-link
+  22198776 Merge pull request #270 from metrumresearchgroup/elapsed-parsing-fixes
-  f090539e Merge pull request #271 from metrumresearchgroup/wire-up-sum-r005
+  b20bb8cd Merge pull request #268 from metrumresearchgroup/objfn-nan
+  75aa1bbe Merge pull request #274 from metrumresearchgroup/run-details-keep-0-time
-  98e28bca Merge pull request #277 from metrumresearchgroup/drone-update-lint
+  75e50208 Merge pull request #272 from …
```
=> NEWS.md: populate with old release notes and add v3.2.0 entries

.drone.yml
.drone.yml builds bbi and copies it to /data/NNN/apps/, and puts that directory at the end of $PATH.  That approach has worked okay for a long time (first occurrence introduced in 3508b4b4, 2020-04-16) because Metworx did not ship with a bbi in any of its PATH directories.  That's no longer the case with the latest Metworx.
Move /data/NNN/apps/ to the front so that the built bbi takes precedence.
---
Thanks to @shairozan for spotting what the issue was.
=> drone: move built bbi's directory to front of PATH

cmd/init.go, cmd/init_test.go, cmd/local.go, cmd/run.go
* `bbi init`: fix two incorrect assumptions that made the detection logic for NONMEM always come up empty
This should be what's behind gh-295.
* `bbi nonmem run local`: invoke bash explicitly so that we don't rely on shebangs and executable files
---
We're still working on getting a Windows machine with NONMEM installed, so both of these haven't been tested directly.  However, I've did the following indirect tests on a Windows machine without NONMEM.
I confirmed that `./bbi.exe init --dir nm/foo` writes out a "nonmem" section with an fake directory that looks like this:
```
$ find nm
nm
nm/foo
nm/foo/bar
nm/foo/bar/license
nm/foo/bar/license/nonmem.lic
nm/foo/bar/run
nm/foo/bar/run/nmfe99.bat
nm/foo/bar/source
nm/foo/bar/util
nm/foo/baz
nm/foo/baz/license
nm/foo/baz/license/nonmem.lic …
```
=> Windows fixes

cmd/init.go, cmd/init_test.go, integration/init_test.go, validation/requirements.yaml
This series was prompted by `bbi init` mishandling a directory with periods.  For example, a directory with the name "7.5.0" will lead to this entry:
```
nonmem:
"7": {}
```
<details>
<summary>demo script</summary>
```sh
#!/bin/sh
set -eu
tdir=$(mktemp -d "${TMPDIR:-/tmp}"/bbi-init-test-XXXXXXX)
test $# != 0 || {
echo "usage: $0 <NONMEM name>"
exit 1
}
cd "$tdir"
for nm_name in "$@"
do
for sdir in license run util source
do
mkdir -p d/"$nm_name"/"$sdir"
done
:> d/"$nm_name"/license/nonmem.lic
:> d/"$nm_name"/run/nmfe75
chmod +x d/"$nm_name"/run/nmfe75
done
bbi init --dir d
cat bbi.yaml
```
```
./demo.sh 7.5.0 | grep nonmem -A1
nonmem:
"7": {}
```
</details>
After the last commit, that will be accessible as "7-5-0".
---
```
init: rename variable for style consistency
init_test: check that …
```
=> init: warn on ID collisions and support NONMEM directories with periods

integration/bbi_local_test.go
When working on gh-307, I noticed that, despite passing, `TestSpecifiedConfigByAbsPathLoaded` and `TestSpecifiedConfigByRelativePathLoaded` have an error in their output:
```
=== RUN   TestSpecifiedConfigByRelativePathLoaded/[INT-LOCAL-006]/acop[INT-LOCAL-006]
INFO[0000] Command was 'bbi' while arguments were -d --config /tmp/bbi-test-w0wYU5G/meow/bbi.yaml nonmem run local --nm_version nm75 /tmp/bbi-test-w0wYU5G/working/acop/acop.mod
ERRO[0000] An error occurred trying to execute model. Error details are : exit status 1
ERRO[0000] Exit code was 1, details were exit status 1
ERRO[0000] output details were: time="2023-10-06T10:01:13-04:00" level=info msg="Successfully loaded specified configuration from /tmp/bbi-test-w0wYU5G/meow/bbi.yaml"
time="2023-10-06T10:01:13-04:00" level=info …
```
=> Fix setup of config file for `TestSpecifiedConfig*` tests

integration/bbi_local_test.go
As of aa686d3 (tests: removing more scenarios from tests that don't need so many divergent paths [...], 2021-09-23), the period_test scenario is no longer used by any tests.  This scenario provides a regression test for a fix in v2.3.1, so it's worth keeping around.
Restore its use in TestBbiCompletesLocalExecution.
=> integration: test period_test scenario

.github/workflows/lint.yml, .golangci.yml, cmd/bbi/main.go, cmd/sge.go, integration/nonmem/bbi_expansion_test.go, integration/nonmem/bbi_local_test.go, integration/nonmem/init_test.go, integration/nonmem/setup.go, integration/postrun/bbi_covcor_test.go, integration/postrun/bbi_params_test.go, integration/postrun/bbi_reclean_test.go, integration/postrun/bbi_summary_test.go, parsers/nmparser/diagonal_elements.go, parsers/nmparser/parse_initial_estimates_test.go, parsers/nmparser/read_ext.go, parsers/nmparser/read_grd.go, runner/consts.go, runner/estimate_model.go, runner/estimate_model_test.go, runner/prepare_to_execute.go, runner/structs.go, utils/expand_sequence.go, utils/io.go
* The incoming valtools branch triggers the lint workflow to fail for reasons related to a dot import.
https://github.com/metrumresearchgroup/bbi/actions/runs/10370260543/job/28707761437
I don't understand why the lint workflow is happy on main but not after that series, but, either way, it's a good idea to use a qualified import, so I just switched to that.
* After that, the lint workflow fails with an obscure error I don't understand:
https://github.com/metrumresearchgroup/bbi/actions/runs/10370823460/job/28709603032
Resolve that by upgrading the lint workflow the latest golangci-lint.  To do that, we need to 1) update the golangci configuration and 2) reformat doc comments in the code base with a newer Go.
=> ci: update lint workflow

cmd/params.go, cmd/root.go
Resolve the two lint workflow failures that popped up here: https://github.com/metrumresearchgroup/bbi/pull/329#issuecomment-2302604560
=> ci: fix lint workflow

cmd/clean.go, cmd/nonmem.go, integration/nmless/bbi_clean_test.go, runner/consts.go
This PR fixes an issue I noticed when working on the `clean` examples for gh-329.
---
=> clean: fix handling of files from *_copied.json

.github/workflows/main.yaml, cmd/bbi/goreleaser.yml
The goreleaser action (added in gh-323) requires version 2 of the config format.
=> Update goreleaser configuration

cmd/init.go, cmd/local.go, cmd/root.go, cmd/sge.go, configlib/config.go, integration/nonmem/data_test.go
Adjust various spots that set the executable bit on files that cannot be executed (e.g., bbi.yaml and {model}.out files).
Close #181.
=> treewide: drop inappropriate executable bits

cmd/local.go, cmd/nonmem.go, cmd/root.go, cmd/run.go, cmd/run_test.go, cmd/sge.go
This series focuses on improving errors reported by `bbi nonmem run {local,sge}`.
The two main improvements make information more available for troubleshooting:
* the underlying error is now included when reporting turnstile.ConcurrentErrors
* even when there is an error, the standard output and standard error for the local and SGE command invocations are written to `{model}.out`
---
=> cmd: improve error reporting

NEWS.md, README.md
changeset: https://github.com/metrumresearchgroup/bbi/compare/b63ceabdeecb34f2b6f7cd761ccc7fc95fccee58...eb49f40525383e37f0f76725c0e09126f3bfe474
<details>
<summary>scores.json (SGE)</summary>
```
$ which sbatch
$ echo $?
1
$ cat internal/valtools/output/bbi_3.3.1-40-geb49f40/bbi_3.3.1-40-geb49f40.scores.json
{
"testing": {
"check": 1,
"coverage": 0.8403502862916806
},
"documentation": {
"has_website": 1,
"has_news": 1
},
"maintenance": {
"has_maintainer": 1,
"news_current": 1
},
"transparency": {
"has_source_control": 1,
"has_bug_reports_url": 1
}
}
```
</details>
<details>
<summary>scores.json (Slurm)</summary>
```
$ which sbatch
/opt/slurm/bin/sbatch
$ cat internal/valtools/output/bbi_3.3.1-40-geb49f40/bbi_3.3.1-40-geb49f40.scores.json
{
"testing": {
"check": 1,
"coverage": …
```
=> Prepare 3.4.0 release
