- cmd/clean.go
- cmd/root.go
- runner/clean_and_copy_est.go
- runner/read_copied_files.go
- runner/read_copied_files_test.go
- runner/testdata/run100_copied.json
- utils/expand_sequence.go
- utils/expand_sequence_test.go
- utils/list_matches.go
- utils/list_matches_test.go
- utils/setup_cache_for_run.go
* implement globbing
* implement cleaning copied files in parent directory for a run
* clean up docs
* change some flags
* slight tweak to pattern expansion to support non-sequential runs
> expand copy mechanics and functionality

- Makefile
- README.md
- cmd/bbi/main.go
- cmd/root.go
> feat: add build support with buildTime sent from Makefile to main.go

- cmd/local.go
- cmd/nonmem.go
- cmd/root.go
- cmd/sge.go
- configlib/config.go
- go.mod
- go.sum
Updating to place a single, converged output file from SGE into the output dir of the directory.
> Adding configs to write SGE output to the output dir of the model

- cmd/init.go
> Updating to default to true if only one nonmem location is found

- cmd/local.go
- cmd/sge.go
Prevents entering turnstile execution phases.
> Fatal error on failure to expand, locate, or setup model

- cmd/nonmem.go
- cmd/nonmem_test.go
- configlib/config.go
Adding some of the NMFE options as `nonmem` command flags. Built unit test for the function that generates the string slice containing the nmfe options. Also built functional test validating the flags end up in the generated script file.
> Nmfe options

- cmd/local.go
- cmd/nonmem.go
* Calculates hash of model file
* Placed that operation into pure function called with channels for data and model
* Updated the model copy function to pass bool of whether or not data location needs to be adjusted based on comparison of model extension
* If it's "mod" we'll add a "../"
* If not, we do nothing
* When evaluating the sanity of the data file, we now fork on similar logic. If it's a "mod" file we look for the data file as it's referenced in the NonMemModel. If it's a CTL we look for it's base representation
> Model hash, file handling for PSN vs Non PSN

- cmd/nonmem.go
- cmd/root.go
Fixing issues with false positives for "not able to locate data file" on the final state of SGE execution (with createChildDirs false)
> Sge execution issues

- .drone.yml
- Dockerfile
Using the NONMEM image on ECR. 
- Levaraging local registry
- Forcing no pull
- Building `nmtest` image locally on drone
> New drone structure

- .drone.yml
Updating drone to write test results (JSON Output) to bucket
> Writing json files

- cmd/local.go
- cmd/nonmem.go
- cmd/root.go
- cmd/sge.go
- configlib/config.go
- docs/bbi/bbi.md
Parallel configs rolled up from their own key in the config to top level components
> Rolling parallel config options up

- cmd/local.go
- cmd/nonmem.go
- cmd/sge.go
- configlib/config.go
Closed the previous pull request. This branch removes the configuration as pointer altogether.
> refactor: removing the configuration as a pointer

- .gitignore
- parsers/nmparser/get_model_output.go
- parsers/nmparser/parse_lst_file.go
- parsers/nmparser/parse_lst_file_test.go
- parsers/nmparser/parse_run_details_test.go
- parsers/nmparser/structs.go
Pulling out the actual condition number instead of just surfacing the heuristic of whether it's > 1000.
> adding condition number to summary

- cmd/covcor.go
- cmd/nonmem.go
- cmd/summary.go
- parsers/nmparser/get_model_output.go
- parsers/nmparser/parse_lst_file.go
- parsers/nmparser/parse_lst_file_test.go
- parsers/nmparser/structs.go
- parsers/nmparser/summary.go
- parsers/nmparser/utils.go
- utils/io.go
- utils/utils.go
Adding the fields requested in https://github.com/metrumresearchgroup/babylon/issues/175
Also, fixed this little guy in this PR: https://github.com/metrumresearchgroup/babylon/issues/79 (It was a one-liner)
> Adding new summary fields August 2020

- README.md
- parsers/nmparser/parse_run_details.go
- parsers/nmparser/structs.go
- parsers/nmparser/summary.go
> Changing patients to subjects in summary output

- .drone.yml
- .golangci.yml
- cmd/nonmem_test.go
- integration/bbi_covcor_test.go
- integration/bbi_expansion_test.go
- integration/bbi_local_test.go
- integration/bbi_sge_test.go
- integration/bbi_summary_test.go
- integration/config_test.go
- integration/data_test.go
- integration/init_test.go
- integration/nmqual_test.go
- integration/postexecution_test.go
- integration/setup.go
- parsers/nmparser/add_path_level.go
- parsers/nmparser/consts.go
- parsers/nmparser/consts_test.go
- parsers/nmparser/parse_lst_file_test.go
- parsers/nmparser/summary_test.go
Tests now have more accurate names in failures that allow us to run one situation at at time.
> Test refinement

- validation/requirements.yaml
- validation/stories.yaml
Prune unlinked requirements, and eliminate requirement ID gaps.
> validation: requirements cleanup

- NEWS.md
changes: https://github.com/metrumresearchgroup/bbi/compare/v3.2.0...71caa91fb6e289057610c4fbb4be26c159f844a3
> NEWS.md: add entry for v3.2.1

- NEWS.md
changes: https://github.com/metrumresearchgroup/bbi/compare/v3.2.2...4479c7c2f8fc6db5bb7d385cb6a2922195056c60
> NEWS.md: add entries for v3.2.3

- cmd/local.go
- cmd/nonmem.go
- integration/nonmem.go
Work towards gh-285.
The base is currently [failing on Drone](https://github-drone.metrumrg.com/metrumresearchgroup/bbi/1021), so that needs to be resolved before moving forward with this.
> Clean up WK_ files

- NEWS.md
changeset: https://github.com/metrumresearchgroup/bbi/compare/8c65e319a1a8e4fa0b213903c22870537c95367b...83c278c91ca5083f5d6d515ed1a0fa5af1370fb4
> Prepare 3.3.0 release

- NEWS.md
changeset: https://github.com/metrumresearchgroup/bbi/compare/835953efed10fff2d7024ac1c3dd88949b268c05...ecafa9334a71c48eb2935fb6879febaba5e4b70b
<details>
<summary>scores.json</summary>
```json
{
"testing": {
"check": 1,
"coverage": 0.8389715832205682
},
"documentation": {
"has_website": 1,
"has_news": 1
},
"maintenance": {
"has_maintainer": 1,
"news_current": 1
},
"transparency": {
"has_source_control": 1,
"has_bug_reports_url": 1
}
}
```
</details>
> Prepare 3.3.1 release
